# Generated by Django 6.0.1 on 2026-01-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('flavor_type', models.CharField(choices=[('milk', 'Mleczny'), ('sorbet', 'Sorbet')], default='milk', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='flavors/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Aktywny'), ('archived', 'Zarchiwizowany')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('display_order', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flavors', models.ManyToManyField(blank=True, to='flavors.flavor')),
                ('hit_of_the_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hit_days', to='flavors.flavor')),
            ],
        ),
    ]
