# Generated by Django 6.0.1 on 2026-01-31 09:08

import apps.flavors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.flavors.models.uuid_upload_to),
        ),
    ]
