# Generated by Django 6.0.1 on 2026-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0002_photo_uuid_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyselection',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
