# Generated by Django 6.0.1 on 2026-02-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0003_dailyselection_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
